Vagrant.configure("2") do |config|

  config.vm.define "wordpress" do |wordpress|
    wordpress.vm.box = "ubuntu/focal64"
    wordpress.vm.hostname = "wordpress"
    wordpress.vm.network "private_network", ip: "192.168.56.26"
    wordpress.vm.network "public_network", bridge: "Realtek RTL8852BE-VS WiFi 6 802.11ax PCIe Adapter"
    wordpress.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end
    wordpress.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y apache2
    SHELL
  end

end
