
Vagrant.configure("2") do |config|

  config.vm.define "portfolio" do |portfolio|
    portfolio.vm.box = "eurolinux-vagrant/centos-stream-9"
    portfolio.vm.hostname = "portfolio"
    portfolio.vm.network "private_network", ip: "192.168.56.16"
    portfolio.vm.network "public_network", bridge: "Realtek RTL8852BE-VS WiFi 6 802.11ax PCIe Adapter"
    portfolio.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end
    portfolio.vm.provision "shell", inline: <<-SHELL
      yum install httpd wget unzip git -y
      mkdir -p /opt/devopsdir
      free -m
      uptime
    SHELL
  end

end
